# permissions for end users to view vmbits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmbit-viewer-role
rules:
- apiGroups:
  - bit.ncg.com
  resources:
  - vmbits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bit.ncg.com
  resources:
  - vmbits/status
  verbs:
  - get
